<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_TimeSlotDelivery
 * @author Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
?>
<?php
    $_order = $block->getOrder();
    if ($_order->getOrderDeliveryDate()):
?>
    <div class="block block-order-details-view">
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo __('Delivery Information') ?></strong>
        </div>
        <div class="block-content">
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Delivery Date') ?></span></strong>
                <div class="box-content">
                    <?php echo $block->escapeHtml($_order->getOrderDeliveryDate()) ?>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Delivery Time') ?></span>
                </strong>
                <div class="box-content">
                    <?php echo $block->escapeHtml($_order->getOrderDeliveryTime()) ?>
                </div>
            </div>
        </div>
    </div>
    <?php endif; ?>