<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
$_product = $block->getProduct();
?>
<?php if ($block->displayProductStockStatus()) : ?>
    <div class="stock__status">
        <?php if ($_product->isAvailable()) : ?>
            <div class="product-info-stock-sku">
                <i class="icon-check"></i>
                <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('In stock')) ?></span>
                </div>
            </div>
        <?php else : ?>
            <div class="product-info-stock-sku">
                <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
                    <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                </div>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>


