<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php if ($block->getMode() == 'grid') : ?>
    <?php
    /**
     * Product list template
     *
     * @var $block \Magento\Catalog\Block\Product\ListProduct
     */
    ?>
    <?php
    //$_productCollection = $block->getLoadedProductCollection();

    ?>

    <?php

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category

    $categoryId = @$category->getId(); // YOUR CATEGORY ID
    $category = $categoryFactory->create()->load($categoryId);

    $_productCollection2 = $category->getProductCollection()
        ->addAttributeToSelect('*');


    ?>

    <?php if (count($_productCollection2)): ?>

        <?php
        /* helper */
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
        $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
        $themeHelper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
        $quickShopHelper = $this->helper('Codazon\QuickShop\Helper\Data');
        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
        $wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
        $labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');

        /* layout */
        $layout = $themeHelper->getBlockPageLayout($block);

        /* show on list */
        $showDescription = $themeHelper->isDisplayOnList('description');
        $showSku = $themeHelper->isDisplayOnList('sku');
        $showWishlist = $themeHelper->isDisplayOnList('wishlist');
        $showCompare = $themeHelper->isDisplayOnList('compare');
        $showCart = $themeHelper->isDisplayOnList('addtocart');
        $showQuickShop = $themeHelper->isDisplayOnList('quickshop');
        $showLabel = $themeHelper->isDisplayOnList('label');
        $showThumb = $themeHelper->isDisplayOnList('thumb');
        $showName = $themeHelper->isDisplayOnList('name');
        $showReview = $themeHelper->isDisplayOnList('review');
        $showPrice = $themeHelper->isDisplayOnList('price');


        $width = $themeHelper->getConfig('images/category/product_image_width') ?: 150;
        $height = $themeHelper->getConfig('images/category/product_image_height') ?: 150;

        $paddingBottom = 65;

        $cartWidget = $block->isRedirectToCartEnabled() ? '' : 'data-mage-init=\'{"catalogAddToCart":{}}\'';


        ?>

        <!---- Get order id by customer  -->
        <?php
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
        $connection = $resource->getConnection();

        //*****************loading Customer session *****************//
        $customerSession = $objectManager->create('Magento\Customer\Model\Session');
        //******** Checking whether customer is logged in or not ********//
        if ($customerSession->isLoggedIn()) {
            $customer_id = $customerSession->getCustomer()->getId();
            // ***********Getting order collection using customer email id ***********//
            $order_collection = $objectManager->create('Magento\Sales\Model\Order')->getCollection()->addAttributeToFilter('customer_id', $customer_id);
            if (count($order_collection) > 0) {
                foreach ($order_collection as $order) {
                    $oid = $order->getEntityId();
                    $item_collection = $objectManager->create('Magento\Sales\Model\Order\Item')->getCollection()->addAttributeToFilter('order_id', $oid);
                    foreach ($item_collection as $item) {
                        $parr[] = $item->getProductId();
                    }
                }

                echo "<h3 class='_block prev__title'>Previously Ordered</h3>";
            } else {
                $parr = [];
            }
        } else {

            $parr = [];
        }
        ?>
        <!---- End  -->
        <?php
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $pos = $block->getPositioned();
        $qtyValidator = $block->escapeHtml(json_encode($themeHelper->getQuantityValidators()));
        ?>

        <div
            class="_block owl-carousel owl-loaded products wrapper product-list-style-19 list-no-hover ctst <?= $viewMode ?> products-<?= $viewMode ?>">
            <?php $iterator = 1; ?>
            <!--Product list wrapper-->
            <ol class="products list items product-items flex-grid pi__list prev__slider"
                data-sameheight=".product-item-details,.product-item-description,.product-item-name">
                <?php foreach ($_productCollection2 as $_product2): ?>
                    <?php if (in_array($_product2->getId(), $parr)) { ?>
                        <?php
                        // Start Custom Qty Dropdown by Prakash
                        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                        $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_product2->getId());
                        $productQty = $productStockObj->getQty();
                        $productMinSaleQty = $productStockObj->getMinSaleQty();
                        $cWeight = $productStockObj->getIsQtyDecimal();
                        if ($cWeight == 1) {
                            $cWeight = "Yes";
                            $productMinQty = .25;
                        } else {
                            $cWeight = "No";
                            $productMinQty = 0;
                        }

                        $qtyArray = 0;
                        $checkQty = ($productQty > 0 && $productQty > $productMinQty) ? ($productQty - $productMinQty) : 0;
                        $customOption = '';
                        $isCustomWeight = ($cWeight == 'Yes') ? 1 : 0;
                        if ($checkQty > 0 && $checkQty > 10):
                            $qtyArray = 10;
                            $moreValue = ($cWeight == 'Yes') ? 8 : 11;
                            $customOption = '<option isweight=' . $isCustomWeight . ' product-id=' . $_product2->getId() . '  value=' . $moreValue . ' class="custom-option">More</option>';
                        elseif ($checkQty > 0 && $checkQty <= 10):
                            $qtyArray = $checkQty;
                        endif;
                        $lbsText = '';
                        $type = ($cWeight == 'Yes') ? 'text' : 'number';
                        $lbOrnot = ($cWeight == 'Yes') ? 'per lb' : '';
                        $optionlb = ($cWeight == 'Yes') ? 'lb' : '';
                        $incressqty = ($cWeight == 'Yes') ? .25 : 1;
                        // End Custom Qty Dropdown by Prakash
                        ?>
                        <!--Custom dropdown PHP logic-->

                        <?= ($iterator++ == 1) ? '<li class="item product product-item pi__wrapper">' : '</li><li class="item product product-item pi__wrapper">' ?>

                        <!--Product card start-->
                        <div class="product-item-info pi__card" data-container="product-grid">
                            <?php if ($showThumb) : ?>
                                <?php
                                $mainImage = $_product2->getData('small_image');
                                $hoveredImage = $_product2->getData('small_image');
                                ?>
                                <?= $showLabel ? $labelHelper->showLabel($_product2) : ''; ?>
                                <div class="product-item-top pi__image-wrapper">
                                    <!--- previos order code by rajeev --->
                                    <?php
                                    //echo "<p style='color:red; font-weight:bold'>Previous ordered</p>";

                                    ?>
                                    <!--Item Image-->
                                    <a href="<?= $_product2->getProductUrl() ?>"
                                       class="product photo product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper"
                                              style="padding-bottom: <?= $paddingBottom ?>%;">
                                           <img class="product-image-photo main-img"
                                                src="<?php echo $imageHelper->init($_product2, $image)->setImageFile($hoveredImage)->resize($width, $height)->getUrl() ?>"/>
                                        </span>
                                    </span>
                                    </a>
                                    <!--Item Image-->

                                    <!--Quick shop icon-->
                                    <?= $showQuickShop ? $quickShopHelper->getQuickShopButton($_product2) : ''; ?>
                                    <!--Quick shop icon-->

                                    <!--Wishlist & compare-->
                                    <?php if ($showCompare || $showWishlist) : ?>
                                        <div class="button-top-wrap">
                                            <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?= $block->getAddToWishlistParams($_product2); ?>'
                                                   class="action towishlist" data-action="add-to-wishlist"
                                                   title="<?= __('Add to Wish List') ?>">
                                                    <span><?= __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <a href="#" class="action tocompare"
                                                   data-post='<?= $compareHelper->getPostDataParams($_product2); ?>'
                                                   title="<?= __('Add to Compare') ?>">
                                                    <span><?= __('Add to Compare') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif ?>
                                    <!--Wishlist & compare-->
                                </div>
                            <?php endif ?>

                            <!--Main content area-->
                            <div class="product details product-item-details pi__details-wrapper">
                                <div class="product-item-inner pi__info">
                                    <!--Item name-->
                                    <?php if ($showName): ?>
                                        <strong class="product name product-item-name _name">
                                            <a class="product-item-link" href="<?= $_product2->getProductUrl(); ?>">
                                                <?= $_helper->productAttribute($_product2, $_product2->getName(), 'name'); ?>
                                            </a>
                                        </strong>
                                    <?php endif ?>


                                    <!--Item SKU-->
                                    <?php if ($showSku) : ?>
                                        <div class="product-item-sku _sku">
                                            <span class="label"><?= __('SKU: ') ?></span>
                                            <span class="value"><?= $_product2->getData('sku') ?></span>
                                        </div>
                                    <?php endif ?>
                                    <?= $showReview ? $block->getReviewsSummaryHtml($_product2, $templateType) : ''; ?>
                                    <?= $showPrice ? $block->getProductPrice($_product2) : ''; ?>
                                    <?php echo $block->getProductDetailsHtml($_product2); ?>

                                    <!--Item description-->
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description _description">
                                            <?= $themeHelper->subString($_helper->productAttribute($_product2, $_product2->getShortDescription(), 'short_description'), 70) ?>
                                        </div>
                                    <?php endif; ?>

                                    <!--Item action area-->
                                    <div class="button-wrap pi__actions-wrapper">
                                        <?php if ($showCart) : ?>
                                            <div class="cart-qty">
                                                <?php if ($_product2->isSaleable()): ?>
                                                    <?php $postParams = $block->getAddToCartPostParams($_product2); ?>
                                                    <form <?= $cartWidget ?>
                                                        data-product-sku="<?= $block->escapeHtml($_product2->getSku()) ?>"
                                                        data-role="tocart-form" action="<?= $postParams['action']; ?>"
                                                        method="post">
                                                        <input type="hidden" name="product"
                                                               value="<?= $postParams['data']['product']; ?>">
                                                        <input type="hidden"
                                                               name="<?= Action::PARAM_NAME_URL_ENCODED; ?>"
                                                               value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey') ?>

                                                        <!--Dropdown or input field-->
                                                        <div class="field qty">
                                                            <label class="label"
                                                                   for="qty"><span>
                                                                <?php /* @escapeNotVerified */
                                                                echo __('Qty') ?></span>
                                                            </label>

                                                            <?php
                                                            // Start Custom Qty Dropdown by Prakash
                                                            if ($_product2->getTypeId() == 'configurable'): ?>
                                                                <?php
                                                                $_children = $_product2->getTypeInstance()->getUsedProductIds($_product2);
                                                                $assoCiatedPro = $_children[0];
                                                                $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($assoCiatedPro);
                                                                $associtedQty = $productStockObj->getQty();
                                                                $customOption = '';
                                                                $moreValue = 11;
                                                                if ($associtedQty > 10):
                                                                    $associtedQty = 10;
                                                                    $customOption = '<option isweight=' . $isCustomWeight . ' product-id=' . $_product2->getId() . '  value=' . $moreValue . ' class="custom-option">More</option>'; endif; ?>
                                                                <select
                                                                    class="control product-qty-<?php echo $_product2->getId(); ?>"
                                                                    name="qty">
                                                                    <?php for ($i = 1; $i <= $associtedQty; $i++): ?>
                                                                        <option
                                                                            value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                                                    <?php endfor; ?>
                                                                    <?php echo $customOption; ?>
                                                                </select>

                                                            <?php elseif ($_product2->getTypeId() == 'bundle' || $_product2->getTypeId() == 'amgiftcard'): ?>
                                                                <?php
                                                                $moreValue = 11;
                                                                $qtyArray = 10;
                                                                $isCustomWeight = 0;
                                                                $customOption = '<option isweight=' . $isCustomWeight . ' product-id=' . $_product2->getId() . '  value=' . $moreValue . ' class="custom-option">More</option>';

                                                                ?>
                                                                <select
                                                                    class="control product-qty-<?php echo $_product2->getId(); ?>"
                                                                    name="qty">
                                                                    <?php if ($qtyArray > 0): $temp = 1; ?>
                                                                        <?php for ($i = 1; $i <= $qtyArray; $i++): ?>
                                                                            <option
                                                                                value="<?php echo $i; ?>"><?php echo $i . $optionlb; ?></option>
                                                                        <?php endfor; ?>
                                                                        <?php echo $customOption; ?>
                                                                    <?php endif; ?>
                                                                </select>
                                                            <?php else: ?>
                                                                <select
                                                                    class="control product-qty-<?php echo $_product2->getId(); ?>"
                                                                    name="qty">
                                                                    <?php if ($qtyArray > 0): $temp = 1; ?>
                                                                        <?php for ($i = 1; $i <= $qtyArray; $i++): ?>
                                                                            <?php
                                                                            $calQty = $i;
                                                                            if ($cWeight == 'Yes') {
                                                                                $calQty = ($i < 5) ? $i / 4 : ++$temp;
                                                                            }
                                                                            ?>
                                                                            <option
                                                                                value="<?php echo $calQty; ?>"><?php echo $calQty . $optionlb; ?></option>
                                                                        <?php endfor; ?>
                                                                        <?php echo $customOption; ?>
                                                                    <?php endif; ?>
                                                                </select>
                                                            <?php endif; ?>

                                                            <div
                                                                class='control custom-button-<?php echo $_product2->getId(); ?> hidden'>
                                                                <div class="qty-ctl">
                                                                    <button type='button'
                                                                            data-action="addto-cart-deduct"
                                                                            title='Remove Product'
                                                                            class='action deductQty-<?php echo $_product2->getId(); ?> decrease'>
                                                                    </button>
                                                                </div>

                                                                <input type='hidden'
                                                                       id='incress-qty-box-po-<?php echo $_product2->getId(); ?>'
                                                                       value="<?php echo $incressqty; ?>" name=''
                                                                       class='qty-box'/>
                                                                <input type='<?php echo $type; ?>'
                                                                       id='qty-box-po-<?php echo $_product2->getId(); ?>'
                                                                       value="" name=''
                                                                       class='qty-box-<?php echo $_product2->getId(); ?>'/>

                                                                <div class="qty-ctl">
                                                                    <button type='button'
                                                                            class='action addQty-<?php echo $_product2->getId(); ?> increase'
                                                                            title='Add'></button>
                                                                </div>
                                                            </div>
                                                            <?php // End Custom Qty Dropdown by Prakash ?>
                                                        </div>
                                                        <!--Dropdown or input field-->

                                                        <button type="submit"
                                                                title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action primary tocart tocart-text pi__add">
                                                            <span class="_icon"></span>
                                                            <span class="_text"><?= __('Add') ?></span>
                                                        </button>
                                                    </form>
                                                <?php else: ?>
                                                    <?php if ($_product2->getIsSalable()): ?>
                                                        <button
                                                            onclick="document.location.href = '<?= $_product2->getProductUrl(); ?>'"
                                                            class="action tocart primary stock available">
                                                            <span><?= __('In stock') ?></span></button>
                                                    <?php else: ?>
                                                        <button class="action tocart primary disabled stock unavailable"
                                                                disabled><span><?= __('Out of stock') ?></span></button>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif ?>
                                        <?php if ($showCompare || $showWishlist) : ?>
                                            <div class="product-extra-buttons hidden">
                                                <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                                    <a href="#"
                                                       data-post='<?= $block->getAddToWishlistParams($_product2); ?>'
                                                       class="action towishlist" data-action="add-to-wishlist"
                                                       title="<?= __('Add to Wish List') ?>">
                                                        <span><?= __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                                <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                    <a href="#" class="action tocompare"
                                                       data-post='<?= $compareHelper->getPostDataParams($_product2); ?>'
                                                       title="<?= __('Add to Compare') ?>">
                                                        <span><?= __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?= ($iterator == count($_productCollection2) + 1) ? '</li>' : '' ?>
                    <?php } ?>
                <?php endforeach; ?>
            </ol>
            <!--Product list wrapper-->
        </div>
        <hr class="rec__sep"/>
    <?php endif; ?>
<?php else : ?>

<?php endif ?>


<script>
    require([
        'jquery',
        'owlslider'
    ], function ($) {
        $(".prev__slider").owlCarousel({
            loop: false,
            margin: 15,
            nav: true,
            dots: false,
            responsive: {
                0: {
                    items: 1,
                    margin: 5,
                    dots: true
                },
                350: {
                    items: 2,
                    margin: 5,
                    dots: true
                },
                640: {
                    items: 2,
                    margin: 5,
                    dots: true
                },
                768: {
                    items: 4
                },
                500: {
                    items: 2
                }
            }
        });
    });
</script>
<style type="text/css">
    .prev__slider {
        overflow: hidden;
        margin: 0 !important;
        margin-bottom: 30px !important;
    }

    .prev__slider .pi__wrapper {
        width: 100% !important;
    }

    .prev__title {
        margin-top: 20px;
    }

    .rec__sep {
        float: left;
        width: 100%;
        margin-top: 0;
        margin-bottom: 30px;
        border: 1px solid #dddbdb;
    }
</style>
