<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!($_count = $_productCollection->count())): ?>
    <div class="message info empty">
        <div><?php /* @escapeNotVerified */
            echo __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

    $showDescription = $this->isShow('description');
    $showSku = $this->isShow('sku');
    $showWishlist = $this->isShow('wishlist');
    $showCompare = $this->isShow('compare');
    $showCart = $this->isShow('addtocart');
    $showQuickShop = $this->isShow('quickshop');
    $showLabel = $this->isShow('label');
    $showThumb = $this->isShow('thumb');
    $showName = $this->isShow('name');
    $showReview = $this->isShow('review');
    $showPrice = $this->isShow('price');

    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
    $wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
    $showSlider = $this->getData('show_slider');

    $width = $block->getData('thumb_width') ?: 150;
    $height = $block->getData('thumb_height') ?: 150;
    //$paddingBottom = $height * 100 / $width;
    $paddingBottom = 65;
    $imageHelper = $this->helper('Magento\Catalog\Helper\Image');
    $quickShopHelper = $this->helper('Codazon\QuickShop\Helper\Data');
    $labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');

    $totalRows = (int)$this->getData('total_rows') ?: 1;
    $totalCols = (int)$this->getData('total_cols');
    $widget = ['themewidgets' => [
        'codazon.slider' => [
            'sliderConfig' => $this->getSliderData(),
            'sameHeight' => ['.product-item-description', '.product-item-name', '.product-reviews-wrap', '.product-item-details']
        ],
    ]];
    $cartWidget = $block->isRedirectToCartEnabled() ? '' : 'data-mage-init=\'{"catalogAddToCart":{}}\'';
    $swatchesRender = $this->getSwatchesBlock();
    $qtyValidator = $block->escapeHtml(json_encode($block->getQuantityValidators()));
    ?>
    <div class="grid-style-17 products wrapper <?= $viewMode; ?> products-<?= $viewMode; ?>">
        <div class="products list items product-items<?= $showSlider ? ' owl-carousel' : '' ?>"
             <?php if ($showSlider) : ?>data-mage-init='<?= json_encode($widget) ?>'<?php endif ?>>
            <?php $i = 0;
            foreach ($_productCollection as $_product): ?>

                <?php
                $randID = rand();
// Start Custom Qty Dropdown by Prakash
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($_product->getId());
                $productQty = $productStockObj->getQty();
                $productMinSaleQty = $productStockObj->getMinSaleQty();
                $cWeight = $productStockObj->getIsQtyDecimal();
                if ($cWeight == 1) {
                    $cWeight = "Yes";
                    $productMinQty = .25;
                } else {
                    $cWeight = "No";
                    $productMinQty = 0;
                }

                $qtyArray = 0;
                $checkQty = ($productQty > 0 && $productQty > $productMinQty) ? ($productQty - $productMinQty) : 0;
//$cWeight = $_product->getResource()->getAttribute('custom_weight_drop_down')->getFrontend()->getValue($_product);
                $customOption = '';
                $isCustomWeight = ($cWeight == 'Yes') ? 1 : 0;
                if ($checkQty > 0 && $checkQty > 10):
                    $qtyArray = 10;
                    $moreValue = ($cWeight == 'Yes') ? 8 : 11;
                    $customOption = '<option isweight=' . $isCustomWeight . ' product-id=' . $randID . '  value=' . $moreValue . ' class="custom-option">More</option>';
                elseif ($checkQty > 0 && $checkQty <= 10):
                    $qtyArray = $checkQty;
                endif;
                $lbsText = '';
                $type = ($cWeight == 'Yes') ? 'text' : 'number';
                $lbOrnot = ($cWeight == 'Yes') ? 'per lb' : '';
                $optionlb = ($cWeight == 'Yes') ? 'lb' : '';
                $incressqty = ($cWeight == 'Yes') ? .25 : 1;

// End Custom Qty Dropdown by Prakash
                ?>
                <?php if ($i % $totalRows == 0) : ?>
                    <div class="item-group cdz-transparent">
                <?php endif ?>
                <div class="item product product-item">
                    <div class="product-item-info pi__card" data-container="product-grid">
                        <?php if ($showThumb) : ?>
                            <?php
                            $mainImage = $_product->getData('small_image');
                            $hoveredImage = $_product->getData('thumbnail');
                            ?>
                            <?= $showLabel ? $labelHelper->showLabel($_product) : ''; ?>

                            <div class="incart_qty hide" id="update_qty-<?php echo $_product->getSku(); ?>">
            <span class="cart-quantity" id="<?php echo $_product->getSku(); ?>"></span><span><?php echo $optionlb;?></span>
            <span class="cart-quantity-summery hide" id="summery-<?php echo $_product->getSku(); ?>" style="display: block; margin-left: 1px;"> in cart</span>
    </div> 
                            <div class="product-item-top pi__image-wrapper">
                                <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper"
                                              style="padding-bottom: <?= $paddingBottom ?>%;">
                                            <img class="product-image-photo main-img"
                                                 src="<?php echo $imageHelper->init($_product, 'category_page_grid')->setImageFile($hoveredImage)->resize($width, $height)->getUrl() ?>"/>
                                        </span>
                                    </span>
                                </a>
                                <?= $showQuickShop ? $quickShopHelper->getQuickShopButton($_product) : ''; ?>
                                <?php if ($showCompare || $showWishlist) : ?>
                                    <div class="button-top-wrap">
                                        <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
                                            <a href="#"
                                               data-post='<?= $block->getAddToWishlistParams($_product); ?>'
                                               class="action towishlist" data-action="add-to-wishlist"
                                               title="<?= __('Add to Wish List') ?>">
                                                <span><?= __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                            <a href="#" class="action tocompare"
                                               data-post='<?= $compareHelper->getPostDataParams($_product); ?>'
                                               title="<?= __('Add to Compare') ?>">
                                                <span><?= __('Add to Compare') ?></span>
                                            </a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif ?>
                            </div>
                        <?php endif ?>

                        <div class="product details product-item-details pi__details-wrapper">
                            <div class="product-item-inner pi__info">
                                <?php if ($showName): ?>
                                    <strong class="product name product-item-name _name">
                                        <a class="product-item-link" href="<?= $_product->getProductUrl(); ?>">
                                            <?= $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                <?php endif ?>
                                <?php if ($showSku) : ?>
                                    <div class="product-item-sku _sku"><span class="label"><?= __('SKU: ') ?></span><span
                                            class="value"><?= $_product->getData('sku') ?></span></div>
                                <?php endif ?>
                                <?= $showReview ? '<div class="product-reviews-wrap">' . $block->getReviewsSummaryHtml($_product, $templateType) . '</div>' : ''; ?>
                                <?= $showPrice ? $block->getProductPrice($_product) : ''; ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description _description">
                                        <?= $this->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 70) ?>
                                    </div>
                                <?php endif; ?>

                                <?php if ($showCart) : ?>
                                    <div class="button-wrap pi__actions-wrapper">
                                        <div class="cart-qty">
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form <?= $cartWidget ?>
                                                    data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                    data-role="tocart-form" action="<?= $postParams['action']; ?>"
                                                    method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?= $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED; ?>"
                                                           value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey') ?>
                                                    <div class="field qty">
                                                        <label class="label"
                                                               for="qty"><span><?php /* @escapeNotVerified */
                                                                echo __('Qty') ?></span></label>
                                                        <?php
                                                        // Start Custom Qty Dropdown by Prakash
                                                        if ($_product->getTypeId() == 'configurable'): ?>
                                                            <?php
                                                            $_children = $_product->getTypeInstance()->getUsedProductIds($_product);
                                                            $assoCiatedPro = $_children[0];
                                                            $productStockObj = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface')->getStockItem($assoCiatedPro);
                                                            $associtedQty = $productStockObj->getQty();
                                                            $customOption = '';
                                                            $moreValue = 11;
                                                            if ($associtedQty > 10):
                                                                $associtedQty = 10;
                                                                $customOption = '<option isweight=' . $isCustomWeight . ' product-id=' . $randID . '  value=' . $moreValue . ' class="custom-option">More</option>';
                                                            endif;
                                                            ?>
                                                            <select
                                                                class="control product-qty-<?php echo $randID; ?>"
                                                                name="qty">
                                                                <?php for ($i = 1; $i <= $associtedQty; $i++): ?>
                                                                    <option
                                                                        value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                                                <?php endfor; ?>
                                                                <?php echo $customOption; ?>
                                                            </select>
                                                        <?php else: ?>
                                                            <select
                                                                class="control product-qty-<?php echo $randID; ?>"
                                                                name="qty">
                                                                <?php if ($qtyArray > 0): $temp = 1; ?>
                                                                    <?php for ($i = 1; $i <= $qtyArray; $i++): ?>
                                                                        <?php
                                                                        $calQty = $i;
                                                                        if ($cWeight == 'Yes') {
                                                                            $calQty = ($i < 5) ? $i / 4 : ++$temp;
                                                                        }
                                                                        ?>
                                                                        <option
                                                                            value="<?php echo $calQty; ?>"><?php echo $calQty . $optionlb; ?></option>
                                                                    <?php endfor; ?>
                                                                    <?php echo $customOption; ?>
                                                                <?php endif; ?>
                                                            </select>
                                                        <?php endif; ?>
                                                        <div
                                                            class='control custom-button-<?php echo $randID; ?> hidden'>
                                                            <div class="qty-ctl">
                                                                <button type='button'
                                                                        data-action="addto-cart-deduct"
                                                                        title='Remove Product'
                                                                        class='action deductQty-<?php echo $randID; ?> decrease'>
                                                                </button>
                                                            </div>

                                                            <input type='hidden'
                                                                   id='incress-qty-box-<?php echo $randID; ?>'
                                                                   value="<?php echo $incressqty; ?>" name=''
                                                                   class='qty-box'/>
                                                            <input type='<?php echo $type; ?>'
                                                                   id='qty-box-<?php echo $randID; ?>'
                                                                   value="" name=''
                                                                   class='qty-box-<?php echo $randID; ?>'/>

                                                            <div class="qty-ctl">
                                                                <button type='button'
                                                                        class='action addQty-<?php echo $randID; ?> increase'
                                                                        title='Add'></button>
                                                            </div>

                                                        </div>
                                                        <?php // End Custom Qty Dropdown by Prakash ?>
                                                    </div>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary tocart-text pi__add">
                                                        <span class="_icon"></span>
                                                        <span class="_text"><?= __('Add') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->getIsSalable()): ?>
                                                    <button
                                                        onclick="document.location.href = '<?= $_product->getProductUrl(); ?>'"
                                                        class="action tocart primary stock available">
                                                        <span><?= __('In stock') ?></span></button>
                                                <?php else: ?>
                                                    <button class="action tocart primary disabled stock unavailable"
                                                            disabled><span><?= __('Out of stock') ?></span></button>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <?php endif ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if (($i % $totalRows == ($totalRows - 1)) || ($i == ($_count - 1))) : ?>
                    </div>
                <?php endif ?>
                <?php $i++; endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<script>
 require(["jquery"], function ($)
 {
        $(document).ready(function() {
              let sid ;
                var interval = setInterval(()=> {
                 $('.cart-quantity-summery,.cart-quantity,.incart_qty').addClass('hide'); 
                 $('.cart-item-qty').each(function(){
                           var $span = $(this);
                           sid = $span.attr('data-cart-item-id'); 
                           
                            $('#update_qty-'+sid).removeClass('hide');
                            $('#summery-'+sid).removeClass('hide');
                            $('#'+sid).removeClass('hide').text($(this).val());
                            clearInterval(interval);
                    });
               }, 5000);
             
        });
});
</script>

