<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<div class="header__category-wrapper">
    <!--Category / Megamenu trigger-->
    <a href="javascript:void(0);" class="header__category-trigger hidden-xs">
        <span class="hamburger">
            <span></span>
            <span></span>
            <span></span>
        </span>
        <span class="label">CATEGORIES</span>
        <span class="arrow"></span>
    </a>
</div>