<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
?>
<?php
/** @var \Magento\Checkout\Block\Onepage $block */
/** @var \Amasty\Checkout\Helper\Onepage $helper */
$helper = $block->getData('amcheckout_helper');
$design = $helper->isModernCheckoutDesign() ? 'modern' : 'classic';
$layout = $helper->getDesignLayout();
?>

<div id="checkout"
     data-bind="scope:'checkout'"
     class="custom__checkout-container checkout-container am-checkout -<?= /* @noEscape */
     $design ?> -layout-<?= /* @noEscape */
     $layout ?>"
     data-amcheckout-js="checkout">
    <div class="checkout-header custom__title">
        <h1 class="title"><?= $block->escapeHtml($helper->getTitle()); ?></h1>
        <div class="description"><?= /* @noEscape */
            $helper->getDescription(); ?></div>
    </div>

    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?=
            /* @noEscape */
            $block->getViewFileUrl('images/loader-1.gif'); ?>"
                 alt="<?= $block->escapeHtml(__('Loading...')); ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */
        $block->getJsLayout(); ?>
            }
        }


    </script>
    <script>
        require.config({
            config: {
                mixins: {
                    'Magento_Ui/js/view/messages': {
                        'Amasty_Checkout/js/view/messages-mixin': true
                    }
                }
            }
        });
        window.checkoutConfig = <?= /* @escapeNotVerified */ \Zend_Json::encode($block->getCheckoutConfig()); ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
        window.checkoutDesign = "<?= $helper->isModernCheckoutDesign() ? 'modern' : 'classic'?>";
        window.checkoutLayout = "<?= $block->escapeHtml($helper->getLayoutTemplate())?>";
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function (url, blockLoader) {
            blockLoader("<?=
                /* @noEscape */ $block->getViewFileUrl('images/loader-1.gif'); ?>");
            return url.setBaseUrl('<?= /* @noEscape */ $block->getBaseUrl();?>');
        });
    </script>

    <?php if ($helper->isAddressSuggestionEnabled() && ($apiKey = $helper->getGoogleMapsKey())): ?>
        <script>
            window.amasty_checkout_regions = <?= /* @noEscape */ $helper->getRegionsJson() ?>;

            function amasty_checkout_gmaps_init() {
                require(['Amasty_Checkout/js/autocomplete'], function (autocomplete) {
                    autocomplete.isReady(true);
                });
            }
        </script>
        <script
                src="https://maps.googleapis.com/maps/api/js?key=<?=
                /* @noEscape */
                $block->stripTags($apiKey); ?>&libraries=places&callback=amasty_checkout_gmaps_init"
                async defer>
        </script>
    <?php endif ?>
</div>

<div class="po__msg">
    <p>In order to improve your shopping experience, we’ve placed a temporary authorization hold of <strong>20%</strong> for the estimated order total on your payment method.</p>

    <p>This will show up as a “pending” charge on your account. During order fulfillment, we may adjust the total
        based on final product weights and approved product substitutions. These changes will be reflected in the
        Final Order Total on the delivery invoice.</p>
</div>



<!--Reload if delivery method not found-->
<!-- <script>
    require(['jquery'], function ($) {
        var methodTable;

        $(window).load(function () {
            logTable();
        });

        // Find elements
        function findTable() {
            methodTable = $(document).find('.table-checkout-shipping-method.amcheckout-shipping-methods .amcheckout-items tr').length;
        }

        // Recursive check for items
        function logTable() {
            // If items found
            if (methodTable) {
                // Do nothing
                if (methodTable < 2) {
                    console.log('will reload');
                    // location.reload();

                } else {
                    console.log('no reload');
                }

            } else {
                setTimeout(function () {
                    findTable();
                    logTable();
                }, 5000);
            }
        }
    });
</script> -->
<!--Reload if delivery method not found-->
